### PR TITLE
Removed a broken link

### PR DESCRIPTION
**Pull request by debugleader**
I spotted a broken link while testing all links.

### CODE REVIEW

**Comment by unseen1980** [comment]
@debugleader Thanks for the PR, would it be possible before merging it to check if they changed URL or if we can replace it
 with some other?

**Comment by debugleader** [comment]
Welcome, I checked but their site is so broken, a lot of buttons don't work and it seems weird

**Comment by debugleader** [comment]
Do you think it's a good idea to merge it and remove the site altogether?

**Comment by debugleader** [comment]
I am not sure if they actually send you notifications or not so for safety reasons, I am gonna tag you @unseen1980

**Comment by unseen1980** [comment]
Yes, let's merge it and if you find some other similar API please add it. Thanks

**Pull request merged**
